#★ SITE CONFIGURATION

#- Using a Custom Domain
url              : "https://hub.newspectrum.dev"
baseurl          : "/"

#- Using GitHub.io
# url              : "https://newspectrum.github.io"
# baseurl          : "/${REPO}"



# THEME-SPECIFIC CONFIGURATION
title: "New Spectrum.dev"
description: ""
avatar: assets/img/nsdev-icon_circle.svg
favicon: assets/favicon.ico

# Header and footer text
header_text: ""
header_feature_image: assets/img/header/triangular.jpeg
header_feature_image_responsive: true
footer_text: >
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

# Blog
excerpt: true
post_navigation: true
color_image: /assets/img/lineart.png  # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true
mermaid: default
google_analytics:            # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false        # To respect the usage of cookies
color_theme: auto

# Comments
comments:
  disqus_shortname:         # Your discus shortname for comments
  cusdis_app_id:            # Your cusdis data-app-id
  utterances:  
  # Enable by filling below information.
  # For more info, go to https://utteranc.es
    repo:            # your public comments repository (e.g. owner/repo)
    issue-term:      # Issue term
	# (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*", "README.md"]


# Tawk.to Chat Integration
#
#  More › https://www.tawk.to/knowledgebase/
#
#  tawk.to is a free live chat app that lets you monitor and chat
#  with visitors on your website or from a free customizable page
#
#  To load the script add 'tawkto: true' in front matter of each page
#
#  used in _includes/footer_scripts

tawkto_embed_uri: https://embed.tawk.to/6413310731ebfa0fe7f30041/1grlff1l5



# theme: type-on-strap      # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap   # For GitHub Pages
